/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import modelo.CuentaSQL;
import modelo.MesaSQL;
import modelo.OrdenSQL;
import modelo.ReservaSQL;
import modelo.Usuario;

/**
 *
 * @author JOCELYNE
 */
public class Cobrar extends javax.swing.JFrame {
CuentaSQL cuesql = new CuentaSQL();
    modelo.Cuenta Cue = new modelo.Cuenta();
    ReservaSQL resql = new ReservaSQL();
    MesaSQL mesql= new MesaSQL();
    OrdenSQL ordsql= new OrdenSQL();
    MenuAtender menu;
    /**
     * Creates new form Cuenta
     */
   // Usuario usr;
    String idCue,IdMe;

     public Cobrar(String idcuenta,String idmesa) {
         
        initComponents();
       // usr=us;
        this.setLocationRelativeTo(null);
        txtNCuenta.setText(idcuenta);
        txtNMesa.setText(idmesa);
        idCue=idcuenta;
        IdMe=idmesa;
        
        
    try {
        cuesql.TablaOrdenId(tblOrden,Integer.parseInt(idcuenta));
       txtTotal.setText(String.valueOf(ordsql.TotalOrdenId(Integer.parseInt(idcuenta)))); 
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(Cobrar.class.getName()).log(Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
        Logger.getLogger(Cobrar.class.getName()).log(Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
        Logger.getLogger(Cobrar.class.getName()).log(Level.SEVERE, null, ex);
    } catch (SQLException ex) {
        Logger.getLogger(Cobrar.class.getName()).log(Level.SEVERE, null, ex);
    }
                 cargartabla();
    }
    public Cobrar() {
        initComponents();
        this.setLocationRelativeTo(null);
         cargartabla();
    }
    public void cargartabla(){
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblMinimizar = new javax.swing.JLabel();
        lblCerrar = new javax.swing.JLabel();
        txtNCuenta = new javax.swing.JTextField();
        txtNMesa = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnCalcularTotal = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrden = new javax.swing.JTable();
        txtTotal = new javax.swing.JTextField();
        txtEfectivo = new javax.swing.JTextField();
        txtCambio = new javax.swing.JTextField();
        btnVolverMenu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblPagarCuenta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1390, 800));
        setUndecorated(true);
        setSize(new java.awt.Dimension(1390, 800));
        getContentPane().setLayout(null);

        jPanel1.setMaximumSize(new java.awt.Dimension(1390, 800));
        jPanel1.setMinimumSize(new java.awt.Dimension(1390, 800));
        jPanel1.setPreferredSize(new java.awt.Dimension(1390, 800));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMinimizar.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 36)); // NOI18N
        lblMinimizar.setForeground(new java.awt.Color(255, 255, 255));
        lblMinimizar.setText("-");
        lblMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizarMouseClicked(evt);
            }
        });
        jPanel1.add(lblMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 10, 20, 30));

        lblCerrar.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 36)); // NOI18N
        lblCerrar.setForeground(new java.awt.Color(255, 255, 255));
        lblCerrar.setText("X");
        lblCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrarMouseClicked(evt);
            }
        });
        jPanel1.add(lblCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 10, 20, 30));

        txtNCuenta.setEditable(false);
        txtNCuenta.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 24)); // NOI18N
        txtNCuenta.setBorder(null);
        jPanel1.add(txtNCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 80, 30));

        txtNMesa.setEditable(false);
        txtNMesa.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 24)); // NOI18N
        txtNMesa.setBorder(null);
        jPanel1.add(txtNMesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 80, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/cobrar.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, -1, -1));

        btnCalcularTotal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/btnPagar.png"))); // NOI18N
        btnCalcularTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularTotalActionPerformed(evt);
            }
        });
        jPanel1.add(btnCalcularTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 480, 200, 50));

        tblOrden.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "PRODUCTO", "CANTIDAD", "PRECIO", "IMPORTE"
            }
        ));
        jScrollPane1.setViewportView(tblOrden);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 110, 590, 240));

        txtTotal.setEditable(false);
        txtTotal.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 22)); // NOI18N
        txtTotal.setBorder(null);
        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });
        jPanel1.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 380, 90, 40));

        txtEfectivo.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 22)); // NOI18N
        txtEfectivo.setBorder(null);
        txtEfectivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEfectivoActionPerformed(evt);
            }
        });
        txtEfectivo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEfectivoKeyReleased(evt);
            }
        });
        jPanel1.add(txtEfectivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 480, 90, 40));

        txtCambio.setEditable(false);
        txtCambio.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 22)); // NOI18N
        txtCambio.setBorder(null);
        txtCambio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCambioActionPerformed(evt);
            }
        });
        jPanel1.add(txtCambio, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 580, 90, 40));

        btnVolverMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/btnVolverMenu.png"))); // NOI18N
        btnVolverMenu.setBorder(null);
        btnVolverMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverMenuActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolverMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 680, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/depagarxd.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 360, -1, 280));

        lblPagarCuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Cuenta.png"))); // NOI18N
        jPanel1.add(lblPagarCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1390, 800));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1390, 800);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizarMouseClicked
        this.setState(JFrame.ICONIFIED); //minimizar la ventana
    }//GEN-LAST:event_lblMinimizarMouseClicked

    private void lblCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseClicked
      if (menu == null) {
            menu = new MenuAtender();
            menu.setVisible(true);
            this.dispose();
        }




        //cerrar la ventana
    }//GEN-LAST:event_lblCerrarMouseClicked

    private void btnCalcularTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularTotalActionPerformed
        if (!txtCambio.getText().equals("")) {
            double total=Double.parseDouble(txtTotal.getText());
double efectivo= Double.parseDouble(txtEfectivo.getText());

            if (efectivo>total) {
                   LocalDate fecha1 = LocalDate.now();
                String fecha;
                if(fecha1.getMonthValue()<10){
                            
                            fecha=fecha1.getDayOfMonth()+"/0"+fecha1.getMonthValue()+"/"+fecha1.getYear();
                        }else{
                            fecha= fecha1.getDayOfMonth()+"/"+fecha1.getMonthValue()+"/"+fecha1.getYear();
                        }
                cuesql.Pagar(Integer.parseInt(idCue));
                resql.EliminarReserva(fecha,Integer.parseInt(IdMe));
                      if (menu == null) {
            menu = new MenuAtender();
            menu.setVisible(true);
            this.dispose();
        }
                
            }else{
            JOptionPane.showMessageDialog(null, "Escriba una cantidad recibida valida");}
            
            
        }else{
        JOptionPane.showMessageDialog(null, "Escriba la cantidad recibida");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnCalcularTotalActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void txtEfectivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEfectivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEfectivoActionPerformed

    private void txtCambioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCambioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCambioActionPerformed

    private void txtEfectivoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEfectivoKeyReleased
double total=Double.parseDouble(txtTotal.getText());
double efectivo= Double.parseDouble(txtEfectivo.getText());
double cambio = efectivo- total;
txtCambio.setText(String.valueOf(cambio));

        // TODO add your handling code here:
    }//GEN-LAST:event_txtEfectivoKeyReleased

    private void btnVolverMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverMenuActionPerformed
        if (menu == null) {
            menu = new MenuAtender();
            menu.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnVolverMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswinlblPagarCuentandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cobrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cobrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cobrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cobrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cobrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcularTotal;
    private javax.swing.JButton btnVolverMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCerrar;
    private javax.swing.JLabel lblMinimizar;
    private javax.swing.JLabel lblPagarCuenta;
    private javax.swing.JTable tblOrden;
    private javax.swing.JTextField txtCambio;
    private javax.swing.JTextField txtEfectivo;
    private javax.swing.JTextField txtNCuenta;
    private javax.swing.JTextField txtNMesa;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
