/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import modelo.Producto;
import modelo.ProductoSQL;

/**
 *
 * @author JOCELYNE
 */
public class Productos extends javax.swing.JFrame {

    modelo.Producto produc = new Producto();
    modelo.ProductoSQL obj = new ProductoSQL();
    Menu menu;

    /**
     * Creates new form Productos
     */
    public Productos() {
        initComponents();
        this.setLocationRelativeTo(null);
        cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnVolverMenu = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        lblCerrar = new javax.swing.JLabel();
        lblMinimizar = new javax.swing.JLabel();
        txtNProducto = new javax.swing.JTextField();
        txtProducto = new javax.swing.JTextField();
        cmbCategoria = new javax.swing.JComboBox<>();
        txtPrecio = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblProductos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1390, 800));
        setMinimumSize(new java.awt.Dimension(1390, 800));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1390, 800));
        setResizable(false);
        setSize(new java.awt.Dimension(1390, 800));
        getContentPane().setLayout(null);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVolverMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/btnVolverMenu.png"))); // NOI18N
        btnVolverMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverMenuActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolverMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 670, 200, 50));

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/btnEliminar.png"))); // NOI18N
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 200, 200, 50));

        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/btnModificar.png"))); // NOI18N
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 100, 200, 50));

        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/btnAgregar.png"))); // NOI18N
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 100, 200, 50));

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/btnBuscar.png"))); // NOI18N
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 200, 200, 50));

        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "IdProducto", "Nombre", "Categoria", "Precio"
            }
        ));
        tblProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProductos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 300, 780, 240));

        lblCerrar.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 36)); // NOI18N
        lblCerrar.setForeground(new java.awt.Color(255, 255, 255));
        lblCerrar.setText("X");
        lblCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrarMouseClicked(evt);
            }
        });
        jPanel1.add(lblCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 10, 20, 30));

        lblMinimizar.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 36)); // NOI18N
        lblMinimizar.setForeground(new java.awt.Color(255, 255, 255));
        lblMinimizar.setText("-");
        lblMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizarMouseClicked(evt);
            }
        });
        jPanel1.add(lblMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 10, 20, 30));

        txtNProducto.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 24)); // NOI18N
        txtNProducto.setBorder(null);
        txtNProducto.setEnabled(false);
        txtNProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNProductoActionPerformed(evt);
            }
        });
        txtNProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNProductoKeyPressed(evt);
            }
        });
        jPanel1.add(txtNProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 150, 80, 50));

        txtProducto.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 24)); // NOI18N
        txtProducto.setBorder(null);
        txtProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtProductoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtProductoKeyTyped(evt);
            }
        });
        jPanel1.add(txtProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 250, 130, 50));

        cmbCategoria.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 24)); // NOI18N
        cmbCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una categoría", "Entradas", "Ensaladas", "Bebidas", "Postres" }));
        cmbCategoria.setBorder(null);
        jPanel1.add(cmbCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 350, 140, 50));

        txtPrecio.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 24)); // NOI18N
        txtPrecio.setBorder(null);
        txtPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioKeyTyped(evt);
            }
        });
        jPanel1.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 450, 80, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/deProductos.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, -1));

        lblProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Productos.png"))); // NOI18N
        lblProductos.setText("jLabel1");
        lblProductos.setMaximumSize(new java.awt.Dimension(1390, 800));
        lblProductos.setMinimumSize(new java.awt.Dimension(1390, 800));
        lblProductos.setPreferredSize(new java.awt.Dimension(1390, 800));
        jPanel1.add(lblProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1390, 800));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1390, 810);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseClicked
        if (menu == null) {
            menu = new Menu();
            menu.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_lblCerrarMouseClicked

    private void lblMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizarMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_lblMinimizarMouseClicked

    public void cargarTabla() {
        try {
            obj.SoloTabla(tblProductos);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        try {

            if (txtProducto.getText() != "" && cmbCategoria.getSelectedIndex() != 0 && txtPrecio.getText() != "") {
                produc.setNombreProducto(txtProducto.getText());
                produc.setCategoriaProducto(cmbCategoria.getSelectedItem().toString());
                produc.setPrecio(Double.parseDouble(txtPrecio.getText()));

                if (obj.RegistrarProducto(produc) == 10) {
                    limpiar();
                }

            } else {

                if (txtProducto.getText().equals("")) {
                    JOptionPane.showMessageDialog(this, "Por favor introduce un nombre para el producto");
                }

                if (cmbCategoria.getSelectedIndex() == 0) {
                    JOptionPane.showMessageDialog(this, "Por favor selecciona una categoria para el producto");
                }

                if (txtPrecio.getText().equals("")) {
                    JOptionPane.showMessageDialog(this, "Por favor introduzca un precio para el producto");
                }
            }

            obj.SoloTabla(tblProductos);

        } catch (NumberFormatException numberFormatException) {
            JOptionPane.showMessageDialog(this, "Por Favor introduzca un precio valido");
            limpiar();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
            limpiar();
        } catch (InstantiationException ex) {
            Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
            limpiar();
        } catch (IllegalAccessException ex) {
            Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
            limpiar();
        } catch (SQLException ex) {
            Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
            limpiar();
        }


    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

        String dato;
        //dato=txtProducto.getText();

        dato = JOptionPane.showInputDialog("Introduce el nombre del producto");
        try {
            obj.BuscarTabla(tblProductos, dato);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtNProductoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNProductoKeyPressed

    }//GEN-LAST:event_txtNProductoKeyPressed


    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        //modificar
        int idproducto = 0;

        try {
            int fila = tblProductos.getSelectedRow();
            if (fila == -1) {
                JOptionPane.showMessageDialog(this, "Por Favor Seleccione un Campo de la Tabla");
            } else {
                idproducto = Integer.parseInt(txtNProducto.getText());
                if (txtProducto.getText().equals("")) {
                    JOptionPane.showMessageDialog(this, "Por favor introduzca el nombre del producto");
                } else {
                    produc.setNombreProducto(txtProducto.getText());
                }
                if (cmbCategoria.getSelectedIndex() == 0) {
                    JOptionPane.showMessageDialog(this, "Por favor selecciona una categoria para el producto");
                } else {
                    produc.setCategoriaProducto(cmbCategoria.getSelectedItem().toString());
                }
                if (txtPrecio.getText().equals("")) {
                    JOptionPane.showMessageDialog(this, "Por favor introduzca un precio para el producto");
                } else {
                    produc.setPrecio(Double.parseDouble(txtPrecio.getText()));
                }
            }

            if (obj.ActualizarProducto(produc, idproducto) == 10) {
                //Se debe enviar unas "comillas" o se envia un null para limpiar
                limpiar();
            }

            obj.SoloTabla(tblProductos);

        } catch (NumberFormatException numberFormatException) {
            JOptionPane.showMessageDialog(this, "Por Favor introduzca un precio valido");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btnModificarActionPerformed

    private void tblProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductosMouseClicked
        if (evt.getButton() == 1) {
            int fila = tblProductos.getSelectedRow();
            String idProducto = (tblProductos.getValueAt(fila, 0).toString());
            String nombreProducto = (tblProductos.getValueAt(fila, 1).toString());
            String categoriaProducto = (tblProductos.getValueAt(fila, 2).toString());
            String precioProducto = (tblProductos.getValueAt(fila, 3).toString());

            txtNProducto.setText(idProducto);
            txtProducto.setText(nombreProducto);
            if (categoriaProducto.equals("Entradas")) {
                cmbCategoria.setSelectedIndex(1);
            }
            if (categoriaProducto.equals("Ensaladas")) {
                cmbCategoria.setSelectedIndex(2);
            }
            if (categoriaProducto.equals("Bebidas")) {
                cmbCategoria.setSelectedIndex(3);
            }
            if (categoriaProducto.equals("Postres")) {
                cmbCategoria.setSelectedIndex(4);
            }
            txtPrecio.setText(precioProducto);

        }


    }//GEN-LAST:event_tblProductosMouseClicked

    public void limpiar() {
        txtNProducto.setText("");
        txtProducto.setText("");
        cmbCategoria.setSelectedIndex(0);
        txtPrecio.setText("");

        try {
            obj.SoloTabla(tblProductos);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
        }

    }


    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

        int borra;

        int fila = tblProductos.getSelectedRow();

        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Por Favor seleccione un Producto de la tabla");
        }

        if (fila != -1) {
            // 0 para si
            // 1 para no
            // 2 para cancelar
            borra = JOptionPane.showConfirmDialog(this, "Esta seguro que desea eliminar este Producto");
            String NomPro = (tblProductos.getValueAt(fila, 1).toString());
            if (borra == 0) {
                produc.setNombreProducto(NomPro);
                obj.Eliminar(produc);
            }
            if (borra==1) {
                JOptionPane.showMessageDialog(this, "El producto no fue eliminado");
            }
            if (borra==2) {
                JOptionPane.showMessageDialog(this, "El producto no fue eliminado");
            }

        }

        limpiar();


    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnVolverMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverMenuActionPerformed
        if (menu == null) {
            menu = new Menu();
            menu.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnVolverMenuActionPerformed

    private void txtNProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNProductoActionPerformed
        //error

    }//GEN-LAST:event_txtNProductoActionPerformed

    private void txtProductoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProductoKeyPressed
        if (evt.getKeyChar() == '\b' && txtProducto.getText().equals("")) {
            txtNProducto.setText("");
            cmbCategoria.setSelectedIndex(0);
            txtPrecio.setText("");
        }


    }//GEN-LAST:event_txtProductoKeyPressed

    private void txtPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioKeyTyped
        char c=evt.getKeyChar();
        if((c<'0'||c>'9')&&(c!='.')) evt.consume();
        
    }//GEN-LAST:event_txtPrecioKeyTyped

    private void txtProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProductoKeyTyped
        char c=evt.getKeyChar();
        if((c<'a'||c>'z')&&(c<'A'||c>'Z')) evt.consume();
    }//GEN-LAST:event_txtProductoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Productos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnVolverMenu;
    private javax.swing.JComboBox<String> cmbCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCerrar;
    private javax.swing.JLabel lblMinimizar;
    private javax.swing.JLabel lblProductos;
    private javax.swing.JTable tblProductos;
    private javax.swing.JTextField txtNProducto;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtProducto;
    // End of variables declaration//GEN-END:variables
}
